### ISSUE TITLE
keep syncing upstream

### ISSUE THREAD

**Issue by explorer3039** [RealTriassic/LinearPaper#2]
Re-enable sync upstream.

**Comment by RealTriassic** [comment]
Apologies for disabling it. Upstream changed something just enough to break one of our patches. I am currently not able to rebase properly to fix the issue, but I will as soon as I get the chance.

**Comment by RealTriassic** [comment]
Merge conflicts solved in https://github.com/StupidCraft/LinearPurpur/commit/73e877c52f98325b1e4844eb7bdb819d8c31f03f and upstream sync has been re-enabled.
