### ISSUE TITLE
[Crash] when the server try to read a chunk data

### ISSUE THREAD

**Issue by pjindras** [RealTriassic/LinearPaper#5]
https://paste.gg/p/anonymous/87fe38d23bf54453bc749186bd71d898

Java 21, minecraft 1.20.4

Nether world entity caused server crash, do you please know what could cause the crash or how to prevent this.
Thank you!

**Comment by RealTriassic** [comment]
This server is not running LinearPurpur, please try to reproduce this with LinearPurpur and see if the issue still persists, otherwise, please report it to [Leaf's GitHub repository](https://github.com/Winds-Studio/Leaf).
