### ISSUE TITLE
1.20.5?

### ISSUE THREAD

**Issue by desplmfao** [RealTriassic/LinearPaper#6]
title

**Comment by RealTriassic** [comment]
Currently waiting for Purpur to release 1.20.5/6 to look into updating this.

**Comment by desplmfao** [comment]
https://github.com/PurpurMC/Purpur/tree/ver/1.20.5

**Comment by RealTriassic** [comment]
> https://github.com/PurpurMC/Purpur/tree/ver/1.20.5

Not even considered Experimental yet, you shouldn't be using it.

**Comment by desplmfao** [comment]
its now the default branch (1.20.6), is it possible for you to update now?

**Comment by RealTriassic** [comment]
It's already being worked on in the [ver/1.20.6](https://github.com/StupidCraft/LinearPurpur/tree/ver/1.20.6) branch, it does not contain the Linear patch at the time of writing this, because I am working on making the patches more maintainable.

**Comment by RealTriassic** [comment]
**Highly experimental** builds are available [here](https://github.com/StupidCraft/LinearPaper/actions?query=branch%3Aver%2F1.20.6), **please do not use this on production servers**

It's based on Paper now and the configuration options are currently stored in Paper's config files, might be changed in the future. It is incomplete, but it will start and successfully load and use Linear worlds (if enabled in paper-world-defaults.yml).

**Comment by RealTriassic** [comment]
1.20.6 branch is now considered stable enough to be the default branch, you can get the latest jar from [here](https://github.com/StupidCraft/LinearPaper/actions?query=branch%3Aver%2F1.20.6), please refer to the README file to see important changes that have been made since during this update.
